services:
  app:
    build: .
    container_name: estudos_docker-app-1
    ports:
      - "5000:5000"
    depends_on:
      - pgdb
      - redis
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgresql://azuledoido:123@pgdb:5432/meubanco
      - REDIS_URL=redis://redis:6379/0
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - TZ=America/Sao_Paulo

  pgdb:
    image: postgres:16  # Mudamos para a 16 (estável)
    container_name: estudos_docker-pgdb-1
    environment:
      POSTGRES_USER: azuledoido
      POSTGRES_PASSWORD: "123"
      POSTGRES_DB: meubanco
      TZ: America/Sao_Paulo
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data # Usando volume nomeado (evita erro de permissão)

  redis:
    image: redis:alpine
    container_name: estudos_docker-redis-1
    environment:
      - TZ=America/Sao_Paulo
    ports:
      - "6379:6379"

volumes:
  pgdata: # Define o volume nomeado